### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by nickdima** [sanex3339/webpack-obfuscator#3]
The latest version from npm (`0.6.1`) installs **javascript-obfuscator** `0.6.0` which has **babel-loader** and **source-map-support** defined as *devDependencies* so they don't get installed and this makes **webpack-obfuscator** break.

**Comment by sanex3339** [comment]
I will fix that in the evening

**Comment by sanex3339** [comment]
fixed 
https://github.com/sanex3339/javascript-obfuscator/commit/a711e1c683a68befebde8e2b33b1733a8128b0e8
