### ISSUE TITLE
Problem installing package on windows 10

### ISSUE THREAD

**Issue by jorgegonzalezperez** [sanex3339/webpack-obfuscator#4]
npm installation doesn't works on Windows 10. Never ends.
I'm using version 4.4.7 of nodejs

**Comment by sanex3339** [comment]
Can you show me NPM log?

**Comment by jorgegonzalezperez** [comment]
no log is generated, just keep running forever

**Comment by sanex3339** [comment]
i.e. after `npm install` you does not see nothing?

**Comment by jorgegonzalezperez** [comment]
no, nothing

**Comment by sanex3339** [comment]
i think this is not a `webpack-obfuscator` problem

**Comment by jorgegonzalezperez** [comment]
I've tried like admin and prune before install and I haven't problem on linux. 
Even trying installing globally.
In other way, I've noticed that it have javascript-obfuscator like dependency that can't install too.
Does anyone have the same problem?
Anyway, I appreciate your help, I know this is difficult to detect.

**Comment by sanex3339** [comment]
If you does not see anything after `npm install` problem not with this package. As i said before, check your npm installation. 

Try to create folder with `test` name. Checkout to this fodert through command line and type:
```
npm init
npm install typescript
```

If you does not see anything too - try to reinstall npm

**Comment by jorgegonzalezperez** [comment]
Hi Sanex.
Since 5 minutes ago the install has gone perfect without change anything. Maybe the problem was with npm server.
Thanks for your time and I'm sorry for the inconveniences.
