### ISSUE TITLE
Source maps

### ISSUE THREAD

**Issue by nickdima** [sanex3339/webpack-obfuscator#5]
I would like to help with making the source maps work via the webpack plugin.
Any known issues that prevented you for doing this before I start looking at it?

**Comment by sanex3339** [comment]
I'l be glad if you take a look at this.

**Comment by nickdima** [comment]
OK, I'll give it a go.

**Comment by nickdima** [comment]
I have a simple example working with sorucemaps. It's quite easy to implement using this module: https://github.com/azu/multi-stage-sourcemap
For now I just hacked by doing this in the `index.js` file:
```js
_this.options.sourceMap = true;
var asset = compilation.assets[file], obfuscationResult = JavaScriptObfuscator.obfuscate(asset.source(), _this.options);
var originalSourceMap = asset.map();
var obfuscationSourceMap = obfuscationResult.getSourceMap();
var transferedSourceMap = transferSourceMap({fromSourceMap: obfuscationSourceMap, toSourceMap: originalSourceMap});
compilation.assets[file] = new SourceMapSource(obfuscationResult.toString(), file, JSON.parse(transferedSourceMap), asset.source(), originalSourceMap);
```
It needs proper checking for an initial sourcemap and all, but you get the point.
Now, I see that your source code is actually a typescript file. I never used that, but I can give it a try and make a pull request after.

**Comment by sanex3339** [comment]
Out in `webpack-obfuscator@0.7.0-dev.4`

Big thanks for help!
